### ISSUE TITLE
A question regarding the cost model

### ISSUE THREAD

**Issue by moderato** [jiazhihao/metaflow_sysml19#1]
Hello, I see in the Metaflow paper that the cost model involves multiple dimensions, e.g. FLOPs, mem usage, kernel launches, etc. However, it looks like in the code only runtime is involved (specifically the Graph::total_cost function in ops.cc). Section 6.1 also said, "The cost model used in the experiments was to minimize execution time." 

I'm wondering why other cost dimensions are not involved in the actual implementation. Or did I miss anything?

Thanks in advance!

**Comment by jiazhihao** [comment]
@moderato You may want to switch to the new codebase https://github.com/jiazhihao/TASO to find the most up-to-date version of the code. When collecting cost, MetaFlow considers run time, mem access, FLOPS, kernel launches, etc. But the current implementation minimizes the execution time. You can change the total_cost function to measure other cost metrics if you prefer to.

**Comment by moderato** [comment]
Sure, I'll take a look at TASO as well. Thank you!
